@startuml

title __CONTROL's Class Diagram__\n

  namespace com.unisa.cinehub {
    namespace control {
      class com.unisa.cinehub.control.CatalogoControl {
          {static} - logger : Logger
          + CatalogoControl()
          + addMiPiace()
          + addRecensione()
          + findAllFilm()
          + findAllPuntate()
          + findAllSerieTv()
          + findFilmById()
          + findMiPiaceById()
          + findMostRecentMedia()
          + findMostVoted()
          + findPuntataById()
          + findPuntataByTitle()
          + findSerieTvById()
          + getNumeroMiPiaceOfRecensione()
          + getNumeroNonMiPiaceOfRecensione()
          + puntataBySerie()
          + puntateByStagione()
          + requestRecensioneById()
          + rispondiARecensione()
          + searchFilmByGenere()
          + searchFilmByTitle()
          + searchSerieTVByGenere()
          + searchSerieTvByTitle()
      }
    }
  }
  

  namespace com.unisa.cinehub {
    namespace control {
      class com.unisa.cinehub.control.GestioneCatalogoControl {
          {static} - logger : Logger
          + GestioneCatalogoControl()
          + addCast()
          + addFilm()
          + addGeneriFilm()
          + addGeneriSerieTv()
          + addPuntata()
          + addRuolo()
          + addSerieTV()
          + findAllCast()
          + findRecensioniByMiPiace()
          + removeCast()
          + removeFilm()
          + removePuntata()
          + removeSerieTV()
          + requestAllRecensioni()
          + updateFilm()
          + updatePuntata()
          + updateSerieTv()
      }
    }
  }
  

  namespace com.unisa.cinehub {
    namespace control {
      class com.unisa.cinehub.control.ModerazioneControl {
          + ModerazioneControl()
          + addSegnalazione()
          + bannaRecensore()
          + deleteRecensione()
          + findAllSegnalazioni()
          + isSegnalated()
      }
    }
  }
  

  namespace com.unisa.cinehub {
    namespace control {
      class com.unisa.cinehub.control.UtenteControl {
          - cal : Calendar
          - eventPublisher : ApplicationEventPublisher
          + UtenteControl()
          + confermaRegistrazione()
          + getAllNotBannedRecensori()
          + getAllRecensori()
          + registrazioneUtente()
      }
    }
  }

  com.unisa.cinehub.control.CatalogoControl o-- com.unisa.cinehub.model.media.film.FilmService : filmService
  com.unisa.cinehub.control.CatalogoControl o-- com.unisa.cinehub.model.utente.MiPiaceService : miPiaceService
  com.unisa.cinehub.control.CatalogoControl o-- com.unisa.cinehub.model.media.serietv.PuntataService : puntataService
  com.unisa.cinehub.control.CatalogoControl o-- com.unisa.cinehub.model.recensione.RecensioneService : recensioneService
  com.unisa.cinehub.control.CatalogoControl o-- com.unisa.cinehub.model.media.serietv.SerieTVService : serieTVService
  com.unisa.cinehub.control.CatalogoControl o-- com.unisa.cinehub.model.utente.UtenteService : utenteService
  com.unisa.cinehub.control.GestioneCatalogoControl o-- com.unisa.cinehub.model.media.CastService : castService
  com.unisa.cinehub.control.GestioneCatalogoControl o-- com.unisa.cinehub.model.media.film.FilmService : filmService
  com.unisa.cinehub.control.GestioneCatalogoControl o-- com.unisa.cinehub.model.media.serietv.PuntataService : puntataService
  com.unisa.cinehub.control.GestioneCatalogoControl o-- com.unisa.cinehub.model.recensione.RecensioneService : recensioneService
  com.unisa.cinehub.control.GestioneCatalogoControl o-- com.unisa.cinehub.model.media.RuoloService : ruoloService
  com.unisa.cinehub.control.GestioneCatalogoControl o-- com.unisa.cinehub.model.media.serietv.SerieTVService : serieTVService
  com.unisa.cinehub.control.ModerazioneControl o-- com.unisa.cinehub.model.recensione.RecensioneService : recensioneService
  com.unisa.cinehub.control.ModerazioneControl o-- com.unisa.cinehub.model.utente.SegnalazioneService : segnalazioneService
  com.unisa.cinehub.control.ModerazioneControl o-- com.unisa.cinehub.model.utente.UtenteService : utenteService
  com.unisa.cinehub.control.UtenteControl o-- com.unisa.cinehub.model.utente.RecensoreService : recensoreService
  com.unisa.cinehub.control.UtenteControl o-- com.unisa.cinehub.model.utente.UtenteService : utenteService


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
